name: Test

on:
  workflow_call: 
    inputs:
      unityVersion:
        required: true
        type: string
      testMode:
        required: true
        type: string        
  workflow_dispatch:
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: copy dir to new dir
        run: |
          pwd
          folderName=$(echo "${PWD##*/}")
          rsync -r "$GITHUB_WORKSPACE" "copiedProject" 
          ls -F "copiedProject/$folderName"

      - name: Run tests
        id: runTests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          packageMode: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ./copiedProject/Flange_Deploy
          unityVersion: ${{ inputs.unityVersion }}
          testMode: ${{ inputs.testMode }}